# Generált leképezés: fajta név -> assets/kep/fajtak/ mappában lévő fájlnév.
# A ChatGPT Image ... .png rácsképből lett kivágva (scripts/ mappán kívüli,
# egyszeri feldolgozással). Csak azok a fajták szerepelnek itt, amelyeknél a
# forráskép egyértelműen (felirat + kinézet alapján) beazonosítható volt.
KEPEK = {
    'Magyar vizsla': 'magyar-vizsla.png',
    'Drótszőrű magyar vizsla': 'drotszoru-magyar-vizsla.png',
    'Puli': 'puli.png',
    'Pumi': 'pumi.png',
    'Mudi': 'mudi.png',
    'Komondor': 'komondor.png',
    'Kuvasz': 'kuvasz.png',
    'Erdélyi kopó': 'erdelyi-kopo.png',
    'Labrador retriever': 'labrador-retriever.png',
    'Golden retriever': 'golden-retriever.png',
    'Border collie': 'border-collie.png',
    'Ausztrál juhászkutya': 'ausztral-juhaszkutya.png',
    'Német juhászkutya': 'nemet-juhaszkutya.png',
    'Belga juhászkutya (malinois)': 'belga-juhaszkutya-malinois.png',
    'Fehér svájci pásztorkutya': 'feher-svajci-pasztorkutya.png',
    'Cane corso': 'cane-corso.png',
    'Rottweiler': 'rottweiler.png',
    'Dobermann': 'dobermann.png',
    'Boxer': 'boxer.png',
    'Bernáthegyi': 'bernathegyi.png',
    'Newfoundlandi kutya': 'newfoundlandi-kutya.png',
    'Nagy svájci hegyikutya': 'nagy-svajci-hegyikutya.png',
    'Leonbergi': 'leonbergi.png',
    'Óriás schnauzer': 'orias-schnauzer.png',
    'Középső schnauzer': 'kozepso-schnauzer.png',
    'Törpeschnauzer': 'torpeschnauzer.png',
    'Airedale terrier': 'airedale-terrier.png',
    'Ír szetter': 'ir-szetter.png',
    'Angol szetter': 'angol-szetter.png',
    'Gordon szetter': 'gordon-szetter.png',
    'Pointer': 'pointer.png',
    'Német drótszőrű vizsla': 'nemet-drotszoru-vizsla.png',
    'Weimari vizsla': 'weimari-vizsla.png',
    'Breton spániel': 'breton-spaniel.png',
    'Cocker spániel': 'cocker-spaniel.png',
    'Springer spániel': 'springer-spaniel.png',
    'Cavalier king charles spániel': 'cavalier-king-charles-spaniel.png',
    'King charles spániel': 'king-charles-spaniel.png',
    'Beagle': 'beagle.png',
    'Basset hound': 'basset-hound.png',
    'Foxhound': 'foxhound.png',
    'Dalmata': 'dalmata.png',
    'Jack russell terrier': 'jack-russell-terrier.png',
    'Parson russell terrier': 'parson-russell-terrier.png',
    'Drótszőrű foxterrier': 'drotszoru-foxterrier.png',
    'Simaszőrű foxterrier': 'simaszoru-foxterrier.png',
    'Yorkshire terrier': 'yorkshire-terrier.png',
    'West highland white terrier': 'west-highland-white-terrier.png',
    'Skót terrier': 'skot-terrier.png',
    'Cairn terrier': 'cairn-terrier.png',
    'Boston terrier': 'boston-terrier.png',
    'Bullterrier': 'bullterrier.png',
    'Staffordshire bullterrier': 'staffordshire-bullterrier.png',
    'Amerikai staffordshire terrier': 'amerikai-staffordshire-terrier.png',
    'Ír terrier': 'ir-terrier.png',
    'Border terrier': 'border-terrier.png',
    'Bichon frisé': 'bichon-frise.png',
    'Máltai selyemkutya': 'maltai-selyemkutya.png',
    'Havanese': 'havanese.png',
    'Törpepudli': 'torpepudli.png',
    'Lagotto romagnolo': 'lagotto-romagnolo.png',
    'Shih tzu': 'shih-tzu.png',
    'Lhasa apso': 'lhasa-apso.png',
    'Tibeti spániel': 'tibeti-spaniel.png',
    'Mopsz': 'mopsz.png',
    'Francia bulldog': 'francia-bulldog.png',
    'Angol bulldog': 'angol-bulldog.png',
    'Basenji': 'basenji.png',
    'Sharpei': 'sharpei.png',
    'Akita inu': 'akita-inu.png',
    'Shiba inu': 'shiba-inu.png',
    'Sziberiai husky': 'sziberiai-husky.png',
    'Alaszkai malamut': 'alaszkai-malamut.png',
    'Szamojéd': 'szamojed.png',
    'Grönlandi kutya': 'gronlandi-kutya.png',
    'Ír farkaskutya': 'ir-farkaskutya.png',
    'Skót szarvasagár': 'skot-szarvasagar.png',
    'Angol agár': 'angol-agar.png',
    'Afgán agár': 'afgan-agar.png',
    'Whippet': 'whippet.png',
    'Spanyol agár': 'spanyol-agar.png',
    'Olasz agár': 'olasz-agar.png',
    'Magyar agár': 'magyar-agar.png',
    'Rodéziai ridgeback': 'rodeziai-ridgeback.png',
    'Bloodhound': 'bloodhound.png',
    'Basset artésien normand': 'basset-artesien-normand.png',
    'Beagle harrier': 'beagle-harrier.png',
    'Törpetacskó': 'torpetacsko.png',
    'Normál tacskó': 'normal-tacsko.png',
    'Chihuahua': 'chihuahua.png',
    'Pomerániai törpespicc': 'pomeraniai-torpespicc.png',
    'Keeshond': 'keeshond.png',
    'Walesi corgi pembroke': 'walesi-corgi-pembroke.png',
    'Walesi corgi cardigan': 'walesi-corgi-cardigan.png',
    'Ausztrál cattle dog': 'ausztral-cattle-dog.png',
    'Ausztrál kelpie': 'ausztral-kelpie.png',
    'Angol ószövegű juhászkutya (bobtail)': 'angol-oszovegu-juhaszkutya-bobtail.png',
    'Shetlandi juhászkutya': 'shetlandi-juhaszkutya.png',
    'Skót juhászkutya (collie)': 'skot-juhaszkutya-collie.png',
    'Beauceron': 'beauceron.png',
    'Briard': 'briard.png',
    'Entlebuchi pásztorkutya': 'entlebuchi-pasztorkutya.png',
    'Appenzelli pásztorkutya': 'appenzelli-pasztorkutya.png',
    'Portugál vízikutya': 'portugal-vizikutya.png',
    'Spanyol vízikutya': 'spanyol-vizikutya.png',
    'Göndörszőrű retriever': 'gondorszoru-retriever.png',
    'Egyenesszőrű retriever': 'egyenesszoru-retriever.png',
    'Nova Scotia Duck Tolling Retriever': 'nova-scotia-duck-tolling-retriever.png',
    'Toy foxterrier': 'toy-foxterrier.png',
    'Manchester terrier': 'manchester-terrier.png',
    'Bedlington terrier': 'bedlington-terrier.png',
    'Skye terrier': 'skye-terrier.png',
    'Norfolk terrier': 'norfolk-terrier.png',
    'Norwich terrier': 'norwich-terrier.png',
    'Ausztrál silky terrier': 'ausztral-silky-terrier.png',
    'Kínai meztelen kutya': 'kinai-meztelen-kutya.png',
    'Amerikai akita': 'amerikai-akita.png',
}
